spring.application.name=s3demo


cloud.aws.credentials.accessKey=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-Key=${AWS_SECRET_KEY}
cloud.aws.region.static=${AWS_REGION}

aws.bucket.name=${AWS_BUCKET_NAME}